name: Build and push

on:
    push:
        branches:
            - main
    pull_request:
        branches:    
            - main

jobs:
    build_and_push:
        name: Build and push docker image
        runs-on: ubuntu-latest 
        steps:
            -   name: Checkout
                uses: actions/checkout@v3  

            -   id: commit
                uses: prompt/actions-commit-hash@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: tang0ch4rlie
                    password: ${{secrets.DOCKERHUB_TOKEN}}
                          
            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: tang0ch4rlie/serrata-discord-bot:latest
                env:
                    PERSONNAL_TOKEN: ${{secrets.PERSONNAL_TOKEN}}
                    CLIENTID: ${{secrets.CLIENTID}}
                    GUILDID: ${{secrets.GUILDID}}
                    TOKEN: ${{secrets.TOKEN}}